name: PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:
  
  check-build-test:

    runs-on: macos-12

    steps:

    - name: Install Tools
      run: |
        brew tap a7ex/homebrew-formulae
        brew install xcbeautify
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1

    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer

    - name: SwiftLint
      run: |
        mkdir .build
        swiftlint lint --reporter json > .build/swiftlint.json

    - name: Build/Test
      run: set -o pipefail && swift test --enable-code-coverage --sanitize undefined | xcbeautify

    - name: Convert Coverage
      run: xcrun llvm-cov show -instr-profile=.build/debug/codecov/default.profdata .build/debug/ShieldPackageTests.xctest/Contents/MacOS/ShieldPackageTests > .build/coverage.report

    - name: Archive Build
      run: tar -czf build.tar.gz .build

    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ github.event.number }}
        path: build.tar.gz

  build-test:

    runs-on: macos-12

    needs: [check-build-test]

    strategy:
      matrix:
        platform: [macos, ios, tvos, watchos]

    steps:

    - name: Install Tools
      run: |
        brew tap a7ex/homebrew-formulae
        brew install xcbeautify findsimulator
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer

    - name: Build/Test
      run: make build-test-${{ matrix.platform }}

    - name: Report Test Results
      uses: kishikawakatsumi/xcresulttool@v1
      if: always()
      continue-on-error: true
      with:
          title: Test Results ${{ matrix.platform }}
          path: ./TestResults/${{ matrix.platform }}.xcresult

