name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        platform: [macOS, iOS, tvOS]
        xcode:
        - '/Applications/Xcode_11.7.app/Contents/Developer'
        - '/Applications/Xcode_12.app/Contents/Developer'
    steps:
    - uses: actions/checkout@v2
    - name: Build & Test
      run: make build-test-${{platform}}
